services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: simulacion_curricular_app
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - simulacion_network
      
  web:
    image: nginx:alpine
    container_name: simulacion_curricular_web
    ports:
      - "8080:80"
    volumes:
      - .:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - simulacion_network

  db:
    image: postgres:15
    container_name: simulacion_curricular_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - simulacion_network

networks:
  simulacion_network:
    driver: bridge

volumes:
  pgdata: