services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simulacion_curricular_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - simulacion_network
    depends_on:
      - postgres
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "80:80"

  postgres:
    image: postgres:15-alpine
    container_name: simulacion_curricular_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - simulacion_network

  redis:
    image: redis:7-alpine
    container_name: simulacion_curricular_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - simulacion_network

networks:
  simulacion_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
